name: catalogs-generator

on:
  push:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions: read-all

defaults:
  run:
    shell: "bash -Eeuo pipefail -x {0}"

jobs:
  generate-catalogs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          pip install packaging==25.0 PyYAML==6.0.2

      - name: Generate catalogs
        run: |
          mkdir image-catalogs && cd image-catalogs
          python ${{ github.workspace }}/.github/catalog_generator.py

      - name: Print
        run: |
          cat image-catalogs/*.yaml
